services:
  prometheus:
    image: prom/prometheus:v3.1.0 # Latest tag 06.01.25
    container_name: prometheus
    ports:
      - "9090:9090"  # Prometheus web UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.4.0 # Latest tag 06.01.25
    container_name: grafana
    ports:
      - "8080:3000"  # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set admin default password for Grafana UI
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data: